name:  Mejora de Documentaci贸n
description: Nueva documentaci贸n o edici贸n de documentaci贸n existente
title: " "
labels: [" documentaci贸n"]
body:
- type: textarea
  attributes:
    label: Motivo
    description: Explicar por qu茅 se deber铆a incluir la documentaci贸n.
  validations:
    required: true
- type: textarea
  attributes:
    label: Partes Afectadas
    description: 驴Qu茅 partes del proyecto cambia/afecta la documentaci贸n?
  validations:
    required: true
- type: textarea
  attributes:
    label: Contexto Adicional
    description: Cualquier informaci贸n extra, como capturas de pantalla, etc.
