name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    name: Create release with tag '${{ github.ref_name }}'
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >
          gh release create '${{ github.ref_name }}'
          --repo '${{ github.repository }}'
          --notes "* [Detalles de Cambios](${{ github.server_url }}/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md#${GITHUB_REF_NAME//./})"
          --generate-notes
          --fail-on-no-commits
