name: Ruff

on: [push]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: astral-sh/ruff-action@v3
      with:
        args: check
        src: "./asistente"
